# Generated by Django 4.2.5 on 2023-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veri',
            name='boy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='veri',
            name='kilo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
